name: Generate Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: hugopm/github-contribution-pacman@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: shoorjitsahoo
          BRANCH: output
          BACKGROUND_COLOR: "#0f0f1a"
          DOT_COLOR: "#818cf8"
          PACMAN_COLOR: "#f97316"
